CREATE TABLE legal_entities (
    "uuid" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    "workspace" VARCHAR(255) NOT NULL DEFAULT '',
    "entity_type" VARCHAR(255) NOT NULL DEFAULT '',
    "logo" VARCHAR(255) NOT NULL DEFAULT '',
    "phone" VARCHAR(20) NOT NULL DEFAULT '',
    "fax" VARCHAR(20) NOT NULL DEFAULT '',
    "email" VARCHAR(255) NOT NULL DEFAULT '',
    "is_vat_payer" BOOLEAN NOT NULL DEFAULT FALSE,
    "full_name" VARCHAR(255) NOT NULL DEFAULT '',
    "short_name" VARCHAR(255) NOT NULL DEFAULT '',
    "inn" VARCHAR(20) NOT NULL DEFAULT '',
    "kpp" VARCHAR(20) NOT NULL DEFAULT '',
    "ogrn" VARCHAR(20) NOT NULL DEFAULT '',
    "okpo" VARCHAR(20) NOT NULL DEFAULT '',
    "legal_address" VARCHAR(255) NOT NULL DEFAULT '',
    "legal_postal_code" VARCHAR(10) NOT NULL DEFAULT '',
    "legal_country" VARCHAR(255) NOT NULL DEFAULT '',
    "legal_region" VARCHAR(255) NOT NULL DEFAULT '',
    "legal_city" VARCHAR(255) NOT NULL DEFAULT '',
    "legal_street" VARCHAR(255) NOT NULL DEFAULT '',
    "legal_house" VARCHAR(10) NOT NULL DEFAULT '',
    "legal_apartment" VARCHAR(10) NOT NULL DEFAULT '',
    "legal_comments" VARCHAR(255) NOT NULL DEFAULT '',
    "actual_address_same_as_legal" BOOLEAN NOT NULL DEFAULT FALSE,
    "actual_postal_code" VARCHAR(10) NOT NULL DEFAULT '',
    "actual_country" VARCHAR(255) NOT NULL DEFAULT '',
    "actual_region" VARCHAR(255) NOT NULL DEFAULT '',
    "actual_city" VARCHAR(255) NOT NULL DEFAULT '',
    "actual_street" VARCHAR(255) NOT NULL DEFAULT '',
    "actual_house" VARCHAR(10) NOT NULL DEFAULT '',
    "actual_apartment" VARCHAR(10) NOT NULL DEFAULT '',
    "actual_comments" VARCHAR(255) NOT NULL DEFAULT '',
    "director_last_name" VARCHAR(255) NOT NULL DEFAULT '',
    "director_first_name" VARCHAR(255) NOT NULL DEFAULT '',
    "director_middle_name" VARCHAR(255) NOT NULL DEFAULT '',
    "director_last_name_genitive" VARCHAR(255) NOT NULL DEFAULT '',
    "director_first_name_genitive" VARCHAR(255) NOT NULL DEFAULT '',
    "director_middle_name_genitive" VARCHAR(255) NOT NULL DEFAULT '',
    "director_position" VARCHAR(255) NOT NULL DEFAULT '',
    "director_signature" VARCHAR(255) NOT NULL DEFAULT '',
    "director_seal" VARCHAR(255) NOT NULL DEFAULT '',
    "accountant_last_name" VARCHAR(255) NOT NULL DEFAULT '',
    "accountant_first_name" VARCHAR(255) NOT NULL DEFAULT '',
    "accountant_middle_name" VARCHAR(255) NOT NULL DEFAULT '',
    "accountant_last_name_genitive" VARCHAR(255) NOT NULL DEFAULT '',
    "accountant_first_name_genitive" VARCHAR(255) NOT NULL DEFAULT '',
    "accountant_middle_name_genitive" VARCHAR(255) NOT NULL DEFAULT '',
    "comments" TEXT NOT NULL DEFAULT '',
    "status" BOOLEAN NOT NULL DEFAULT TRUE,
    "created_by" VARCHAR(255) NOT NULL DEFAULT '',
    "created_by_uuid" uuid NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    "deleted_at" timestamptz,
    "company_uuid" uuid,
    "federation_uuid" uuid NOT NULL REFERENCES "public"."federations"("uuid") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "legal_entities_federation_uuid_company_uuid_deleted_at_idx" ON legal_entities ("federation_uuid", "company_uuid") WHERE "deleted_at" IS NULL;
