ALTER TABLE public.legal_entities
ADD COLUMN mail_index VARCHAR(10) NOT NULL DEFAULT '',
ADD COLUMN mail_country VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN mail_region VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN mail_city VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN mail_street VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN mail_house VARCHAR(10) NOT NULL DEFAULT '',
ADD COLUMN mail_apartment VARCHAR(10) NOT NULL DEFAULT '',
ADD COLUMN mail_comments VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN mail_address_same_as_legal BOOLEAN NOT NULL DEFAULT FALSE;
