ALTER TABLE public.legal_entities
ADD COLUMN first_name VARCHAR(255) DEFAULT NULL,
ADD COLUMN last_name VARCHAR(255) DEFAULT NULL,
ADD COLUMN middle_name VARCHAR(255) DEFAULT NULL,
ADD COLUMN document_type VARCHAR(255) DEFAULT NULL,
ADD COLUMN document_series VARCHAR(20) DEFAULT NULL,
ADD COLUMN document_number VARCHAR(20) DEFAULT NULL,
ADD COLUMN document_issuer VARCHAR(255) DEFAULT NULL,
ADD COLUMN document_issue_date DATE DEFAULT NULL,
ADD COLUMN document_department_code VARCHAR(20) DEFAULT NULL,
ADD COLUMN ogrnip VARCHAR(20) DEFAULT NULL,
ADD COLUMN certificate_number VARCHAR(255) DEFAULT NULL,
ADD COLUMN certificate_date DATE DEFAULT NULL;